//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Markato.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTeamHistory
    {
        public int ID { get; set; }
        public int TeamID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public int Req { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Team Team { get; set; }
    }
}
